name: build-and-test

on: [ push ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Elm
        run: npm i elm@0.19.1-5 elm-test@0.19.1-revision12

      - name: Build Website
        run: npx elm make src/Main.elm --optimize

      - name: Run Tests
        run: npx elm-test

      - name: Deploy
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ Deployment.HOST }}
          username: ${{ Deployment.USERNAME }}
          key: ${{ Deployment.KEY }}
          port: ${{ Deployment.PORT }}
          source: "index.html"
          target: /var/www/spotify-backup/public/index.html
