name: build-and-test

on: [ push ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: Deployment

    steps:
      - uses: actions/checkout@v2

      - name: Install Elm
        run: npm i elm@0.19.1-5 elm-test@0.19.1-revision12

      - name: Build Website
        run: npx elm make src/Main.elm --optimize

      - name: Run Tests
        run: npx elm-test

      - name: Deploy
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "index.html"
          target: "/var/www/spotify-backup/public"
          overwrite: true
