name: build-and-test

on: [ push ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Elm
        run: npm i elm@0.19.1-3 elm-test@0.19.1-revision2

      - name: Build Website
        run: npx elm make src/Main.elm --optimize

      - name: Run Tests
        run: npx elm-test
