name: build-and-test

on: [ push ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: Deployment

    steps:
      - uses: actions/checkout@v2

      - name: Install Elm
        run: npm i elm@0.19.1-5 elm-test@0.19.1-revision12

      - name: Build Website
        run: npx elm make src/Main.elm --optimize

      - name: Run Tests
        run: npx elm-test

      - name: Deploy
        run: |
          echo "${{ secrets.KEY }}" > id_rsa
          chmod 0600 id_rsa
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i ./id_rsa index.html ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/spotify-backup/public
          rm -f id_rsa
